# Triggers
TriggerMap:
  TPG Enabled CRP4:
    attribute_name: tp_generation_enabled
    class_name: ReadoutApplication
    object_names: [runp02srv003eth0]
    enabled: true
    enabled_state: true
    disabled_state: false

  TPG Enabled CRP5:
    attribute_name: tp_generation_enabled
    class_name: ReadoutApplication
    object_names: [runp02srv003eth1]
    enabled: true
    enabled_state: true
    disabled_state: false

  TPA Enabled:
    attribute_name: ta_generation_enabled
    class_name: ReadoutApplication
    object_names: null
    enabled: true
    enabled_state: true
    disabled_state: false

# Detector Subsystems
DetectorSystemMap:
  CRP4:
    subsystems:
      - type: component
        class: Segment
        id: crp4-segment
        enabled_state: true
        disabled_state: false
    enabled: true
  
  CRP5:
    subsystems:
      - type: component
        class: Segment
        id: crp5-segment
        enabled_state: true
        disabled_state: false
    enabled: true

  APA 1:
    subsystems:
      - type: component
        class: Segment
        id: apa1-segment
        enabled_state: true
        disabled_state: false
    enabled: true

  APA 2:
    subsystems:
      - type: component
        class: Segment
        id: apa2-segment
        enabled_state: true
        disabled_state: false
    enabled: true
  APA 3:
    subsystems:
      - type: component
        class: Segment
        id: apa3-segment
        enabled_state: true
        disabled_state: false
    enabled: true

  APA 4:
    subsystems:
      - type: component
        class: Segment
        id: apa4-segment
        enabled_state: true
        disabled_state: false
    enabled: true
