# Demo
# Any system can be defined in the following way
# FullSystemName:
#   subsystems:
#     - type: component/relationship/attribute
#       class: ClassName: (e.g. Segment, ReadoutApplication, DFApplication): Affected class or class of specific object
#       id: Name of class or attribute
#       enabled_state: State of the class or attribute when enabled
#       disabled_state: State of the class or attribute when disabled
#       relationship_name: Name of the relationship [Only for relationship]
#       affected_objects: List of objects affected by the trigger [Only for attribute]
#  enabled: true/false default enable/disable state if the system is defined incorrectly in the configuration file

# Triggers
TriggerMap:

  TPG:
    subsystems:
      - id: tp_generation_enabled
        type: attribute
        class: ReadoutApplication
        affected_objects: [runp02srv001eth0, runp02srv002eth0]
        enabled_state: true
        disabled_state: false
      - id: ta_generation_enabled
        type: attribute
        affected_objects: [runp02srv001eth0, runp02srv002eth0]
        class: ReadoutApplication
        enabled_state: true
        disabled_state: false
      - id: tc-maker-tpc
        class: TriggerApplication
        type: component
        enabled_state: true
        disabled_state: false
      - id: tp-stream-writer
        class: TPStreamWriterApplication
        type: component
        enabled_state: true
        disabled_state: false
    enabled: true

# Detector Subsystems
DetectorSystemMap:
  CRP4:
    subsystems:
      - type: component
        class: Segment
        id: crp4-segment
        enabled_state: true
        disabled_state: false
    enabled: true
  
  CRP5:
    subsystems:
      - type: component
        class: Segment
        id: crp5-segment
        enabled_state: true
        disabled_state: false
    enabled: true

  PDS:
    subsystems:
      - type: component
        class: Segment
        id: pds-segment
        enabled_state: true
        disabled_state: false
    enabled: true


  APA 1:
    subsystems:
      - type: component
        class: Segment
        enabled_state: true
        disabled_state: false
    enabled: true

  APA 2:
    subsystems:
      - type: component
        class: Segment
        id: apa2-segment
        enabled_state: true
        disabled_state: false
    enabled: true
  APA 3:
    subsystems:
      - type: component
        class: Segment
        id: apa3-segment
        enabled_state: true
        disabled_state: false
    enabled: true

  APA 4:
    subsystems:
      - type: component
        class: Segment
        id: apa4-segment
        enabled_state: true
        disabled_state: false
    enabled: true
