'''
Exceptions
'''

class RunconfUIException(Exception): ...

class IncompatibleDalException(RunconfUIException):...

class RunconfUIAttributeException(RunconfUIException):...

class IncorrectAttributeException(RunconfUIAttributeException): ...

class AttributeValueException(RunconfUIAttributeException): ...