"""
Exceptions
"""


# Generic runconf ui exception
class _RunconfUIException(Exception): ...


# ------- State Ops -------- #
# Set of exceptions for state operations
# Generic bad state exception, shouldn't be called
class _RunConfUIStateException(_RunconfUIException): ... 
# DAL is incompatible for a given property
class IncompatibleDalException(_RunConfUIStateException): ...
# Generic attribute exception
class _RunconfUIAttributeException(_RunConfUIStateException): ...
# Attribute is missing
class AttributeMissingException(_RunconfUIAttributeException): ...
# Attribute value is wrong
class AttributeValueException(_RunconfUIAttributeException): ...
# For subsystem errors
class __RunConfUISubsystemException(_RunConfUIStateException): ...
# Subssytems are 1:1 so you shouldn't be able to have two labeled in a StateOperationController
class DuplicatedSubsystemException(__RunConfUISubsystemException): ...
# Subsystems require labels
class SubsystemLabelError(__RunConfUISubsystemException): ...
# Cannot bind a state twice
class StateBindingError(_RunConfUIStateException):...

# ------- Repo Management -------- #
# Set of exceptions for repo management
class _RunConfUIRepoException(_RunconfUIException): ...
# When you select a bad DAQ version
class DaqVersionException(_RunConfUIRepoException): ...
# When you find a repo with no settings
class MissingRunconfUIConfigException(_RunConfUIRepoException): ...
# When the user doesn't set runconf-tools repo
class RunConfToolsRepoException(_RunConfUIRepoException): ...
# When the config doesn't exist
class ConfigNotFoundInRepoException(_RunConfUIRepoException): ...
# When there is no session
class ConfigBrokenInRepoException(_RunConfUIRepoException): ...

# ------- Configuration Errors -------- #
class _DaqConfigException(_RunconfUIException): ...
# Error when reading config
class ConfigReadException(_DaqConfigException): ...
# Error when writing to config
class ConfigWriteException(_DaqConfigException): ...
# When runconf-tools repos aren't linked
