---
# Optionw to generate panels
PanelOptions:

  Detector:
    label: "detector"
    view_panel: "Detector View"
    panel_type: "multisystem"

    Systems:
      - TPC:
          subsystem_dependent: True
          components:
            - id: tpc-segment
              class: Segment
            - id: crp4-segment
              class: Segment
              system_label: CRP4
              separate_system: True

            - id: crp5-segment
              class: Segment
              system_label: CRP5
              separate_system: True

      - PDS:
          components:
            - id: pds-segment
              class: Segment

      - CTB:
          components:
            - id: ctb-segment
              class: Segment

  TPG:
    label: "TPG"
    view_panel: "TPG View"
    panel_type: "multisystem"

    Systems:
      - TPG:
          subsystem_dependent: True
          display_full_system: False

          components:
            - id: tc-maker-tpc
              class: TriggerApplication

            - id: tp-stream-writer
              class: TPStreamWriterApplication

          attributes:
            - id: tp_generation_enabled
              segments: ["tpc-segment"]
              class: ReadoutApplication
              system_label: TPC
              separate_system: True

            - id: ta_generation_enabled
              segments: ["tpc-segment", "crp4-segment", "crp5-segment"]
              class: ReadoutApplication
              system_label: TPC
              separate_system: True

            - id: tp_generation_enabled
              segments: ["pds-segment"] 
              class: ReadoutApplication
              system_label: PDS
              separate_system: True

  Trigger:
    label: "Trigger"
    panel_type: "singlesystem"
    classes:
      - "CTBHLT"
    filters:
      - description: "spare"
      - description: "Spare"

  # Dataflow
  Dataflow:
    label: "dataflow"
    panel_type: "singlesystem"
    classes:
      - "DFApplication"