---
# Options to generate panels
Settings:
  classes_to_show:
    - Segment
    - SmartDaqApplication
    - CTBHLT
    - CTBoardConf


PanelOptions:
  Detector:
    label: "detector"
    view_panel: "Detector View"

    Systems:
      - TPC:
          subsystem_dependent: True
          components:
            - id: tpc-segment
              class: Segment
            - id: crp4-segment
              class: Segment
              system_label: CRP4
              separate_system: True

            - id: crp5-segment
              class: Segment
              system_label: CRP5
              separate_system: True

      - PDS:
          subsystem_dependent: True
          components:
            - id: pds-segment
              class: Segment

            - id: membrane-segment
              class: Segment
              system_label: Membrane
              separate_system: True

            - id: cathode-segment
              class: Segment
              system_label: Cathode
              separate_system: True

      - CTB:
          components:
            - id: ctb-segment
              class: Segment

  TPG:
    label: "TPG"
    view_panel: "TPG View"

    Systems:
      - TPG:
          subsystem_dependent: True
          display_full_system: True

          components:
            - id: tc-maker-tpc
              class: TriggerApplication

            - id: tp-stream-writer
              class: TPStreamWriterApplication

          attributes:
            - id: tp_generation_enabled
              segments: ["tpc-segment"]
              class: ReadoutApplication
              system_label: TPC
              separate_system: True

            - id: ta_generation_enabled
              segments: ["tpc-segment", "crp4-segment", "crp5-segment"]
              class: ReadoutApplication
              system_label: TPC
              separate_system: True

            - id: tp_generation_enabled
              segments: ["pds-segment"]
              class: ReadoutApplication
              system_label: PDS
              separate_system: True

  TPG:
    label: "trigger"
    view_panel: "Trigger View"
    Systems:

      - RandomTrigger:
          relationships:
            - id: standalone_candidate_maker_confs
              class: MLTApplication
              segments: ['trg-segment']
              relationship_class: RandomTCMakerConf
              enabled_state: [random-tc-generator]
              disabled_state: []
              tooltip: "Enable/Disable random trigger"

      - Trigger:
          display_full_system: False
          subsystem_dependent: False
          components:
            - id: ""
              class: CTBHLT
              each_component_separate: True
              filters:
                - attribute: "description"
                  values: ["Spare", "spare"]
              tooltip: 'description'
  # Dataflow
  Dataflow:
    label: "dataflow"
    Systems:
      - Dataflow:
          subsystem_dependent: False
          display_full_system: False
          components:
            - id: ""
              class: "DFApplication"
              each_component_separate: True


AdjustableAttributes:
  Random Trigger Rates:
    label: "TriggerRates"
    Systems:
      - object_id: "random-tc-generator"
        object_class: RandomTCMakerConf
        attribute_name: "trigger_rate_hz"
        unit_label: "Hz"

  Prescales:
    label: "PreScales"
    Systems:
      - object_class: "CTBHLT"
        attribute_name: "prescale"
        is_hex: True
        unit_label: ""
        filters:
          - attribute: "description"
            values: ["Spare", "spare"]

        tooltip: 'description'
