---
Settings:
  classes_to_show:
    - Segment
    - TriggerApplication
    - TPStreamWriterApplication
    - ReadoutApplication
    - MLTApplication
    - RandomTCMakerConf
    - CTBHLT
    - DFApplication
    - CTBoardConf
    - DetectorStream

PanelOptions:
  Detector:
    label: "detector"
    view_panel: "Detector View"

    Systems:
      - TPC:
          subsystem_dependent: True
          components:
            - id: tpc-segment
              class: Segment
           
            - id: apa1-segment
              class: Segment
              system_label: APA1
              separate_system: True

            - id: apa2-segment
              class: Segment
              system_label: APA2
              separate_system: True

            - id: apa3-segment
              class: Segment
              system_label: APA3
              separate_system: True

            - id: apa4-segment
              class: Segment
              system_label: APA4
              separate_system: True

      - PDS:
          components:
            - id: pds-segment
              class: Segment

  # Dataflow
  Dataflow:
    label: "dataflow"
    Systems:
      - Dataflow:
          subsystem_dependent: True
          display_full_system: False
          components:
            - id: ""
              class: "DFApplication"
              each_component_separate: True

  Trigger:
    label: "trigger"
    view_panel: "Trigger View"

    Systems:
      - TPG:
          subsystem_dependent: True
          display_full_system: False

          components:
            - id: tc-maker-tpc
              class: TriggerApplication

            - id: tp-stream-writer
              class: TPStreamWriterApplication

          attributes:
            - id: tp_generation_enabled
              segments: ["tpc-segment"]
              class: ReadoutApplication
              system_label: TPC
              separate_system: True

            - id: ta_generation_enabled
              segments: ["tpc-segment", "crp4-segment", "crp5-segment"]
              class: ReadoutApplication
              system_label: TPC
              separate_system: True

            - id: tp_generation_enabled
              segments: ["pds-segment"]
              class: ReadoutApplication
              system_label: PDS
              separate_system: True

AdjustableAttributes:
  Random Trigger Rates:
    label: "TriggerRates"
    Systems:
      - object_id: "random-tc-generator"
        object_class: RandomTCMakerConf
        attribute_name: "trigger_rate_hz"
        unit_label: "Hz"

