---
General:
  # Environment variables
  default_config: "SESSION_FILE"
  download_directory: "CONFIG_DIR"
  session_name: "SESSION_NAME"

  default_daq_version: "EHN1_DEFAULT_VERSION"
  default_daq_config: "EHN1_DEFAULT_CONFIG"

  base_url: "https://gitlab.cern.ch/dune-daq/online/ehn1-daqconfigs"
  operation_url: "https://gitlab.cern.ch/dune-daq/online/np02-configs-operation.git"

PanelOptions:

  Detector:
    label: "detector"
    view_panel: "Detector View"
    panel_type: "multisystem"

    Systems:
      - TPC:
          components:
            - id: tpc-segment
              class: Segment
            - id: crp4-segment
              class: Segment
              system_label: CRP4
              separate_system: True

            - id: crp5-segment
              class: Segment
              system_label: CRP5
              separate_system: True

      - PDS:
          components:
            - id: pds-segment
              class: Segment

  # Dataflow
  Dataflow:
    label: "dataflow"
    panel_type: "singlesystem"
    classes:
      - "DFApplication"


  Trigger:
    label: "trigger"
    view_panel: "Trigger View"
    panel_type: "multisystem"

    Systems:
      - TPC TPG:
          attributes:
              - id: tp_generation_enabled
                segments: ["tpc-segment", "crp4-segment", "crp5-segment"]
                class: ReadoutApplication

              - id: ta_generation_enabled
                segments: ["tpc-segment", "crp4-segment", "crp5-segment"]
                class: ReadoutApplication

          components:
            - id: tc-maker-tpc
              class: TriggerApplication
            - id: tp-stream-writer
              class: TPStreamWriterApplication

      - PDS TPG:
          attributes:
              - id: tp_generation_enabled
                segments: ["pds-segment"]
                class: ReadoutApplication
    
              - id: ta_generation_enabled
                segments: ["pds-segment"]
                class: ReadoutApplication

