---
General:
  # Environment variables

  # Default .data.xml configuration file
  default_config: "SESSION_FILE"
  # Default download directory for DAQ configuration files OR local directory containing configurations
  download_directory: "CONFIG_DIR"
  # Name of TMUX session
  session_name: "SESSION_NAME"

  ## CONFIGURATION MANAGER  SETTINGS

  # Grabs git branch "default_daq_version/default_daq_config"

  # Default DAQ version 
  default_daq_version: "EHN1_DEFAULT_VERSION"
  # Default DAQ configuration file 
  default_daq_config: "EHN1_DEFAULT_CONFIG"

  # URL containing git repos
  base_url: "https://gitlab.cern.ch/dune-daq/online/ehn1-daqconfigs"
  # URL containing git repos for the operation configuration
  operation_url: "https://gitlab.cern.ch/dune-daq/online/np02-configs-operation.git"

# Optionw to generate panels
PanelOptions:

  Detector:
    label: "detector"
    view_panel: "Detector View"
    panel_type: "multisystem"

    Systems:
      - TPC:
          components:
            - id: tpc-segment
              class: Segment
            - id: crp4-segment
              class: Segment
              system_label: CRP4
              separate_system: True

            - id: crp5-segment
              class: Segment
              system_label: CRP5
              separate_system: True

      - PDS:
          components:
            - id: pds-segment
              class: Segment

  # Dataflow
  Dataflow:
    label: "dataflow"
    panel_type: "singlesystem"
    classes:
      - "DFApplication"


  Trigger:
    label: "trigger"
    view_panel: "Trigger View"
    panel_type: "multisystem"

    Systems:
      - TPC TPG:
          attributes:
              - id: tp_generation_enabled
                segments: ["tpc-segment", "crp4-segment", "crp5-segment"]
                class: ReadoutApplication

              - id: ta_generation_enabled
                segments: ["tpc-segment", "crp4-segment", "crp5-segment"]
                class: ReadoutApplication

          components:
            - id: tc-maker-tpc
              class: TriggerApplication
            - id: tp-stream-writer
              class: TPStreamWriterApplication

      - PDS TPG:
          attributes:
              - id: tp_generation_enabled
                segments: ["pds-segment"]
                class: ReadoutApplication
    
              - id: ta_generation_enabled
                segments: ["pds-segment"]
                class: ReadoutApplication

