General:
  # Environment variables
  default_config: "SESSION_FILE"
  download_directory: "CONFIG_DIR"
  session_name: "SESSION_NAME"

  base_url: "https://gitlab.cern.ch/dune-daq/online/ehn1-daqconfigs"
  operation_url: "https://gitlab.cern.ch/dune-daq/online/np02-configs-operation.git"