---
General:
  # Default .data.xml configuration file
  session_config: "np02-session.data.xml"
  # Default download directory for DAQ configuration files OR local directory containing configurations
  download_directory: "shifter_view_configs"
  # Name of TMUX session
  session_name: "shifter_view_configs"

  # URL for the git repository containing the DAQ configuration files
  base_url: "https://gitlab.cern.ch/dune-daq/online/ehn1-daqconfigs"
  operation_url: "https://gitlab.cern.ch/dune-daq/online/np02-configs-operation.git"
